# Generated by Django 4.2 on 2023-04-16 13:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="subscriptions",
            field=models.ManyToManyField(blank=True, related_name="related_to", to=settings.AUTH_USER_MODEL),
        ),
    ]
